DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"pass" character varying(64)
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO twitter_user;

REVOKE ALL ON users FROM public;
GRANT ALL ON users TO twitter_user;

