DROP TABLE IF EXISTS dishes CASCADE;
CREATE TABLE dishes (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"price" integer,
"type" integer
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO menuqr_user;

REVOKE ALL ON dishes FROM public;
GRANT ALL ON dishes TO menuqr_user;